name: orbit_task_ios
description: "iOS implementation for the orbit_task plugin."
version: 0.0.1
homepage: https://github.com/rickhohler/orbit_task
repository: https://github.com/rickhohler/orbit_task/tree/main/packages/orbit_task_ios
issue_tracker: https://github.com/rickhohler/orbit_task/issues

environment:
  sdk: ^3.10.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  orbit_task_platform_interface: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    implements: orbit_task
    platforms:
      ios:
        pluginClass: OrbitTaskIosPlugin
