name: orbit_task_web
description: "Web implementation for the orbit_task plugin, providing fallback simulation for background tasks in the browser."
version: 0.0.1+5
homepage: https://github.com/rickhohler/orbit_task
repository: https://github.com/rickhohler/orbit_task/tree/main/packages/orbit_task_web
issue_tracker: https://github.com/rickhohler/orbit_task/issues

environment:
  sdk: ^3.10.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  orbit_task_platform_interface: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  fake_async: ^1.3.1

flutter:
  plugin:
    implements: orbit_task
    platforms:
      web:
        pluginClass: OrbitTaskWebWeb
        fileName: orbit_task_web.dart
