name: orbit_task_platform_interface
description: "Common platform interface definitions for the orbit_task federated plugin ecosystem."
version: 0.0.3
homepage: https://github.com/rickhohler/orbit_task
repository: https://github.com/rickhohler/orbit_task/tree/main/packages/orbit_task_platform_interface
issue_tracker: https://github.com/rickhohler/orbit_task/issues

environment:
  sdk: ^3.10.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
