name: orbit_task_generator
description: "Code generator for the orbit_task package."
version: 0.0.1
homepage: https://github.com/rickhohler/orbit_task
repository: https://github.com/rickhohler/orbit_task/tree/main/packages/orbit_task_generator
issue_tracker: https://github.com/rickhohler/orbit_task/issues

environment:
  sdk: ^3.10.3
  flutter: ">=1.17.0"

dependencies:
  build: ^2.4.1
  source_gen: ^1.4.0
  analyzer: ^6.2.0
  orbit_task_annotations: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
