name: orbit_task
description: "The Next Generation Task Scheduler for Flutter. Orchestrate background execution seamlessly across Android, iOS, and Web."
version: 0.0.1+2
homepage: https://github.com/rickhohler/orbit_task
repository: https://github.com/rickhohler/orbit_task
issue_tracker: https://github.com/rickhohler/orbit_task/issues

environment:
  sdk: ^3.10.3
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.2
  orbit_task_platform_interface: ^0.0.1
  orbit_task_android: ^0.0.1
  orbit_task_ios: ^0.0.1
  orbit_task_web: ^0.0.1

flutter:
  plugin:
    platforms:
      android:
        default_package: orbit_task_android
      ios:
        default_package: orbit_task_ios
      web:
        default_package: orbit_task_web


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.6.1
  build_runner: ^2.10.4
  plugin_platform_interface: ^2.1.8
