name: orbit_task_annotations
description: "Annotation library for orbit_task, allowing easy designation of background task handler functions."
version: 0.0.2
homepage: https://github.com/rickhohler/orbit_task
repository: https://github.com/rickhohler/orbit_task/tree/main/packages/orbit_task_annotations
issue_tracker: https://github.com/rickhohler/orbit_task/issues

environment:
  sdk: ^3.10.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
